Numpy
======

In [3]:
# numpy is a widely used numerical 
# package for python
import numpy as np

Arrays
-------

In [1]:
import numpy as np
# numpy arrays are the basic data structure of numpy
# We can easily do vector additions with numpy arrays
a = np.array([1,2,3])
b = np.array([4,3,3])
a + b

array([5, 5, 6])

In [21]:
# ... work out the dot product
a.dot(b) # 4 + 6 + 9

19

Numpy functions
-------------

In [3]:
import numpy as np
# We can apply numpy funcitons
# entry wise to arrays in a very easy way
#
# This is useful when plotting data
#
# Example:
a = np.array([0,1,2,3,4,5,6,7,8,9,10])
b = np.sin(a)
c = np.sqrt(a)

In [4]:
# b == [sin(0), sin(1), sin(2), ... , sin(10)]
b

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [17]:
# c == [√0, √1, √2, ... ]
c

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

Matrices
-----------

In [22]:
import numpy as np
# Matrices are two dimensional numpy arrays
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

In [23]:
# We can access the twoth column of M
M[:,2]

array([3, 6, 9])

In [24]:
# We can access the oneth row of M
M[1,:]

array([4, 5, 6])

In [25]:
# We can compute A.x
a = np.array([1,2,3,])
M.dot(a)

array([14, 32, 50])

In [26]:
# ... and multiply matrices together
M.dot(M)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [27]:
# WARNING! The * operator does entrywise multiplication!
M*M

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [28]:
# Swapping rows is easy.
# The following swaps rows 0 and 1
M[[1,0],:] = M[[0,1],:] 

In [29]:
M

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [30]:
# Swapping columns is easy.
# The following swaps columns 1 and 2
M[:,[1,2]] = M[:,[2,1]]

In [31]:
M

array([[4, 6, 5],
       [1, 3, 2],
       [7, 9, 8]])

In [32]:
# We can also do row operations
# E.g., We replace the twoth row with 
# 4 times the twoth row - 7 times the zeroth row
M[2,:] = 4*M[2,:] - 7*M[0,:]

In [33]:
M

array([[ 4,  6,  5],
       [ 1,  3,  2],
       [ 0, -6, -3]])

In [34]:
# ... transposing is also easy
Mtranspose = M.transpose()
Mtranspose

array([[ 4,  1,  0],
       [ 6,  3, -6],
       [ 5,  2, -3]])