Numpy
======

Numpy is a widely used external package for doing matrix computations. It is designed to be very fast.

Arrays
-------

Arrays is the basic datastructure of numpy. We can think of them as vectors.

In [3]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,3,3])
a + b

array([5, 5, 6])

... we can compute the dot product:

In [4]:

a.dot(b) # 4 + 6 + 9

19

Numpy functions
-------------

Numpy provides many mathematical functions like numpy.sin, numpy.cos, etc. When applying these to arrays, they are applied entry-wise. This is useful for plotting.

In [5]:
import numpy as np

a = np.array([0,1,2,3,4,5,6,7,8,9,10])
b = np.sin(a)
c = np.sqrt(a)

In [6]:
# b == [sin(0), sin(1), sin(2), ... , sin(10)]
b

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [7]:
# c == [sqrt(0), sqrt(1), sqrt(2), ... , sqrt(10)]
c

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

Matrices
-----------

Matrices can be represented as 2D numpy arrays

In [12]:
import numpy as np

M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

We can access columns, e.g., the twoth column:

In [13]:
M[:,2]

array([3, 6, 9])

We can access columns, e.g., the oneth row:

In [15]:

M[1,:]

array([4, 5, 6])

We can compute multiply a matrix with a vector using the .dot function: 

In [17]:
v = np.array([1,2,3,])
M.dot(v)

array([14, 32, 50])

We can multiply a matrix with another matrix, also using the .dot function :

In [18]:
M.dot(M)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

Waring: The * operator does entrywise multiplication!

In [19]:
M*M

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

## Matrix row/column operations

Consider:

In [24]:
import numpy as np

M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])



We can easily perform row/column swaps. 

The following swaps the zeroth and oneth rows of M:

In [25]:
M[[1,0],:] = M[[0,1],:] 

In [26]:
M

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

The following swaps the oneth and twoth columns of M:

In [27]:
M[:,[1,2]] = M[:,[2,1]]

In [29]:
M

array([[4, 6, 5],
       [1, 3, 2],
       [7, 9, 8]])

... and we can perform elementary row operations (e.g., for implementing Gauss elimination).  

The following  replaces the twoth row with 
 4 times the twoth row - 7 times the zeroth row

In [30]:
M[2,:] = 4*M[2,:] - 7*M[0,:]

In [31]:
M

array([[ 4,  6,  5],
       [ 1,  3,  2],
       [ 0, -6, -3]])

Transposing is easy.

In [33]:
M.transpose()


array([[ 4,  1,  0],
       [ 6,  3, -6],
       [ 5,  2, -3]])